// Generated by CoffeeScript 1.7.1
(function() {
  var hello, one, should;

  should = require('chai').should();

  hello = require('../hello');

  one = hello.one;

  describe('#one', function() {
    return it('does one', function() {
      return one.should.equal(1);
    });
  });

}).call(this);
