// Generated by CoffeeScript 1.7.1
(function() {
  var Bishop, Board, King, Knight, Pawn, Queen, Rook;

  King = require('./pieces/king');

  Queen = require('./pieces/queen');

  Rook = require('./pieces/rook');

  Bishop = require('./pieces/bishop');

  Knight = require('./pieces/knight');

  Pawn = require('./pieces/pawn');

  Board = (function() {
    function Board() {
      this.initialize_board();
      this.initialize_pieces();
    }

    Board.prototype.initialize_board = function() {
      var $, _;
      return this.board = (function() {
        var _i, _results;
        _results = [];
        for ($ = _i = 0; _i <= 23; $ = ++_i) {
          _results.push((function() {
            var _j, _results1;
            _results1 = [];
            for (_ = _j = 0; _j <= 5; _ = ++_j) {
              _results1.push(null);
            }
            return _results1;
          })());
        }
        return _results;
      })();
    };

    Board.prototype.initialize_pieces = function() {
      var color, colors, i, pieces, _i, _j, _results;
      colors = ['white', 'black', 'grey'];
      pieces = [King, Queen, Rook, Bishop, Knight, Pawn];
      _results = [];
      for (color = _i = 0; _i <= 2; color = ++_i) {
        pieces = [Rook, Knight, Bishop, King, Queen, Bishop, Knight, Rook];
        for (i = _j = 0; _j <= 7; i = ++_j) {
          this.board[8 * color + i][0] = new pieces[i]({
            color: colors[color],
            board: this
          });
        }
        _results.push((function() {
          var _k, _results1;
          _results1 = [];
          for (i = _k = 0; _k <= 7; i = ++_k) {
            _results1.push(this.board[8 * color + i][1] = new Pawn({
              color: colors[color],
              board: this
            }));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    return Board;

  })();

  module.exports = Board;

}).call(this);
