// Generated by CoffeeScript 1.7.1
(function() {
  var Board;

  Board = (function() {
    function Board() {
      this.initialize_board();
      this.initialize_pieces();
    }

    Board.prototype.initialize_board = function() {
      var $, _;
      return this.board = (function() {
        var _i, _results;
        _results = [];
        for ($ = _i = 0; _i <= 23; $ = ++_i) {
          _results.push((function() {
            var _j, _results1;
            _results1 = [];
            for (_ = _j = 0; _j <= 5; _ = ++_j) {
              _results1.push(null);
            }
            return _results1;
          })());
        }
        return _results;
      })();
    };

    Board.prototype.initialize_pieces = function() {};

    return Board;

  })();

  module.exports = Board;

}).call(this);
