// Generated by CoffeeScript 1.7.1
(function() {
  var Pawn, Piece,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Piece = require('piece');

  Pawn = (function(_super) {
    __extends(Pawn, _super);

    function Pawn(opts) {
      Pawn.__super__.constructor.apply(this, arguments);
      this.type = 'pawn';
    }

    return Pawn;

  })(Piece);

  module.exports = Pawn;

}).call(this);
