// Generated by CoffeeScript 1.7.1
(function() {
  var Pawn, Piece,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Piece = require('./piece');

  Pawn = (function(_super) {
    __extends(Pawn, _super);

    function Pawn(opts) {
      Pawn.__super__.constructor.apply(this, arguments);
      this.initialize_direction();
      this.type = 'pawn';
    }


    /*
     * With pawns, we must be careful about the direction in which
     * they move forward. For example, if a pawn crosses the inner circle
     * it is moving "backward" in relation to the pawns that started on that
     * side, which are moving forward.
     *
     * To record this moving direction, we simply maintain the convention that
     * @direction = 1 implies the pawn is moving toward the center, and
     * @direction = -1 implies the pawn is moving away from the center.
     *
     * A pawn changes direction if and only if it crosses the center circle.
     */

    Pawn.prototype.initialize_direction = function() {
      return this.direction = 1;
    };

    return Pawn;

  })(Piece);

  module.exports = Pawn;

}).call(this);
