// Generated by CoffeeScript 1.7.1
(function() {
  var Piece,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Piece = (function() {
    function Piece(opts) {
      this.assign_color(opts);
      this.assign_board(opts);
    }

    Piece.prototype.assign_color = function(opts) {
      var color, colors;
      if (__indexOf.call(opts, 'color') < 0) {
        throw "Please provide a piece color";
      }
      color = opts.color.toLowerCase();
      if (__indexOf.call(colors = ['white', 'black', 'grey'], color) < 0) {
        throw "Piece color must be one of " + (colors.join(', '));
      }
      return this.color = color;
    };

    Piece.prototype.assign_board = function(opts) {
      if (__indexOf.call(opts, 'board') < 0) {
        throw "Please provide a board";
      }
      if (opts.board.constructor.name !== 'Board') {
        throw "Specified 'board' is not a Board";
      }
      return this.board = opts.board;
    };

    return Piece;

  })();

  module.exports = Piece;

}).call(this);
