// Generated by CoffeeScript 1.7.1
(function() {
  var chess, engine, should;

  should = require('chai').should();

  engine = require('../../engine/index');

  chess = engine.Chess;

  describe('#chess', function() {
    return it("should chess", function() {
      return (chess()).should.equal(1);
    });
  });

}).call(this);
